root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "tmp/air"
  cmd = "templ generate && go build -o ./tmp/air ./cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "database", "scripts", "tasks"]
  exclude_regex = ["_test.go", "_templ.go"]
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
