version: '3'

dotenv:
  - .env

includes:
  os_specific: ./tasks/taskfile_{{ OS }}.yaml

vars:
  GO_RUN_PATH: ./cmd/main.go

tasks:
  default:
    cmds:
      - echo "Running the application"
      - templ generate
      - go run {{ .GO_RUN_PATH }}
    silent: true
  
  serve:
    cmds:
      - air -c .air_{{ OS }}.toml
    silent: true

  build:
    cmds:
      - templ generate
      - go build -o {{ .EXE_PATH }} {{ .GO_RUN_PATH }}
      - echo "Application build"
    silent: true

  start:
    cmds:
      - ./{{ .EXE_PATH }}
    silent: true

  run:
    cmds:
      - echo "Building and running the application"
      - task build
      - task start
    silent: true

  docker:
    cmds:
      - docker-compose up -d
      - echo "Docker containers started"
    silent: true

  docker-stop:
    cmds:
      - docker-compose down
      - echo "Docker containers stopped"
    silent: true

  docker-build:
    cmds:
      - echo "Building Docker containers"
      - templ generate
      - docker-compose up --build
    silent: true
  
  docker-rebuild:
    cmds:
      - echo "Rebuilding Docker containers"
      - docker-compose down
      - templ generate
      - docker-compose up --build --force-recreate
    silent: true

  db:
    cmds:
      - echo "Resetting the database"
      - python{{ .PYTHON }} ./scripts/fresh_db.py
    silent: true
  
  seed:
    cmds:
      - echo "Seeding the database"
      - python{{ .PYTHON }} ./scripts/seed_db.py {{ .CLI_ARGS }}
    silent: true

  clean:
    cmds:
      - echo "Cleaning application"
      - rm -rf ./bin
      - rm -rf ./tmp
    silent: true